#!/usr/bin/env python3

import sys
import unicodedata
from pathlib import Path


UNICODE_VERSION = "16.0.0"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "lib/src/core/unicode-data.valk"


def ranges_for(values):
    ranges = []
    for value in values:
        if ranges and value == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], value)
        else:
            ranges.append((value, value))
    return ranges


def mapping_for(mode):
    singles = []
    expansions = []
    for code in range(sys.maxunicode + 1):
        source = chr(code)
        mapped = getattr(source, mode)()
        if mapped == source:
            continue
        points = tuple(ord(char) for char in mapped)
        if len(points) == 1:
            singles.append((code, points[0]))
        else:
            expansions.append((code, points))

    lookup = dict(singles)
    used = set()
    runs = []
    for step in (1, 2):
        for code, target in singles:
            if code in used:
                continue
            delta = target - code
            run = []
            current = code
            while current in lookup and current not in used and lookup[current] - current == delta:
                run.append(current)
                current += step
            if len(run) >= 3:
                runs.append((run[0], run[-1], step, target))
                used.update(run)

    return sorted(runs), [item for item in singles if item[0] not in used], expansions


def emit_table(name, values):
    # Six hexadecimal digits cover every Unicode scalar and every table offset.
    # A string literal keeps the bootstrap compiler from recursively lowering
    # thousands of Array initializer calls.
    encoded = "".join(f"{value:06x}" for value in values)
    return f'global {name}: String ("{encoded}")'


def flatten(items):
    return [value for item in items for value in item]


def emit_mapping(prefix, mode):
    runs, singles, expansions = mapping_for(mode)
    expansion_records = []
    expansion_values = []
    for code, points in expansions:
        expansion_records.append((code, len(expansion_values), len(points)))
        expansion_values.extend(points)
    return "\n\n".join((
        emit_table(f"unicode_{prefix}_ranges", flatten(runs)),
        emit_table(f"unicode_{prefix}_singles", flatten(singles)),
        emit_table(f"unicode_{prefix}_expansions", flatten(expansion_records)),
        emit_table(f"unicode_{prefix}_expansion_values", expansion_values),
    ))


def validate_mapping(mode):
    runs, singles, expansions = mapping_for(mode)
    decoded = dict(singles)
    decoded.update((code, points) for code, points in expansions)
    for first, last, step, target in runs:
        for code in range(first, last + 1, step):
            decoded[code] = target + code - first
    for code in range(sys.maxunicode + 1):
        source = chr(code)
        expected = tuple(ord(char) for char in getattr(source, mode)())
        actual = decoded.get(code, code)
        if not isinstance(actual, tuple):
            actual = (actual,)
        if actual != expected:
            raise AssertionError(f"bad {mode} mapping for U+{code:04X}: {actual} != {expected}")


def is_cased(char):
    return char.islower() or char.isupper() or char.istitle()


def is_case_ignorable(code):
    char = chr(code)
    if is_cased(char):
        return False
    # Python applies Unicode's Final_Sigma rule. If this character does not
    # interrupt the preceding-cased scan, it has Case_Ignorable=True.
    return ("A" + char + "Σ").lower().endswith("ς")


def main():
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"expected Unicode {UNICODE_VERSION}, found {unicodedata.unidata_version}"
        )

    validate_mapping("lower")
    validate_mapping("upper")

    alpha = ranges_for(code for code in range(sys.maxunicode + 1) if chr(code).isalpha())
    alnum = ranges_for(code for code in range(sys.maxunicode + 1) if chr(code).isalnum())
    cased = ranges_for(code for code in range(sys.maxunicode + 1) if is_cased(chr(code)))
    ignorable = ranges_for(code for code in range(sys.maxunicode + 1) if is_case_ignorable(code))

    contents = "\n\n".join((
        "// Generated by misc/generate-unicode.py from Unicode 16.0.0.\n"
        "// Each property table stores inclusive start/end pairs. Mapping range\n"
        "// records store start, end, step and the mapped value for start.",
        emit_table("unicode_alpha_ranges", flatten(alpha)),
        emit_table("unicode_alnum_ranges", flatten(alnum)),
        emit_table("unicode_cased_ranges", flatten(cased)),
        emit_table("unicode_case_ignorable_ranges", flatten(ignorable)),
        emit_mapping("lower", "lower"),
        emit_mapping("upper", "upper"),
    )) + "\n"
    OUTPUT.write_text(contents)


if __name__ == "__main__":
    main()
