#!/usr/bin/env python3

"""Generate the cached powers used by Valk's shortest float formatter."""

POWER_BITS = 125
INVERSE_COUNT = 292
POWER_COUNT = 327
MASK64 = (1 << 64) - 1

HEADER = """// Generated by misc/generate-float-cache.py. Do not edit manually.
// Float conversion table derived from Ryu.
// Copyright 2018 Ulf Adams
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
"""


def split(value: int) -> tuple[int, int]:
    return value >> 64, value & MASK64


def normalized_power_of_five(exponent: int) -> int:
    value = 5**exponent
    shift = POWER_BITS - value.bit_length()
    if shift >= 0:
        return value << shift
    divisor = 1 << -shift
    return (value + divisor - 1) // divisor


def inverse_power_of_five(exponent: int) -> int:
    power = 5**exponent
    shift = POWER_BITS + power.bit_length() - 1
    return ((1 << shift) + power - 1) // power


def emit_table(name: str, values: list[int]) -> None:
    print(f"global {name}: [u64 x {len(values) * 2}] ({{")
    for value in values:
        high, low = split(value)
        print(f"    0x{high:016x}, 0x{low:016x}")
    print("})")


print(HEADER)
values = [inverse_power_of_five(i) for i in range(INVERSE_COUNT)]
values += [normalized_power_of_five(i) for i in range(POWER_COUNT)]
emit_table("float_cached_powers", values)
