version: 2.1

# Define the jobs we want to run for this project
jobs:
  linux-x64:
    docker:
      - image: cimg/base:2025.02
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install llvm-15
      - run: sudo apt-get install lld

      - run: "wget -q https://cdn.valk-lang.dev/releases/valk/legacy/valk-legacy-linux-x64.tar.gz"
      - run: mkdir -p ~/valk-legacy
      - run: tar -xf valk-legacy-linux-x64.tar.gz -C ~/valk-legacy
      - run: sudo ln -s -f ~/valk-legacy/valk /usr/local/bin/valk-legacy

      - run: make ci_linux
      - run: mkdir -p ./debug
      - run: make test


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - linux-x64