# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  linux-x64:
    name: "Test on linux-x64"
    machine: true
    no_output_timeout: 5m
    steps:
      - checkout
      - run:
        name: Install LLVM 15
        command: sudo apt-get update && sudo apt-get install llvm-15

      - run:
        name: Install lld
        command: sudo apt-get install lld

      - run: 
        name: Get legacy compiler
        command: wget -q https://cdn.valk-lang.dev/releases/valk/legacy/valk-legacy-linux-x64.tar.gz
      - run: mkdir -p ~/valk-legacy
      - run: tar -xf valk-legacy-linux-x64.tar.gz -C ~/valk-legacy
      - run: ln -s -f ~/valk-legacy/valk /usr/local/bin/valk-legacy

      - name: Build valk
        run: make

      - name: Run test
        run: make test
