<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(GcTargetFramework)' == ''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(GcTargetFramework)' != ''">$(GcTargetFramework)</TargetFramework>
    <AssemblyName>gc-csharp</AssemblyName>
    <RootNamespace>GcBench</RootNamespace>
    <Nullable>disable</Nullable>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
